### ISSUE TITLE
${workspaceRoot}/.pylintrc is not loaded by pylint

### ISSUE THREAD

**Issue by bbenoist** [DonJayamanne/pythonVSCode#117]
Hi,

The `.pylintrc` file I placed at workspace root is not loaded when the extension invokes pylint on source files.

`.pylintrc` syntax is correct and the file is correctly loaded when calling pylint from the command-line in the same workspace root directory. I expected the vscode extension to act the same...

Isn't the linter called with this location as working directory?

**Comment by bbenoist** [comment]
In [`pylint.ts:86`]( https://github.com/DonJayamanne/pythonVSCode/blob/master/src/server/linters/pylint.ts#L86):

```typescript
var dir = path.dirname(filePath);  
//var cmd: string = `${PYLINT_COMMANDLINE} ${filePath}`; 
exec(cmd,{cwd:dir}, (error: Error, stdout: string, stderr: string) => { 
```

Why is `path.dirname(filePath)` the value for `cwd`?

**Comment by DonJayamanne** [comment]
Agreed, that's incorrect. Thanks
Fixed and will be in the next build.

**Comment by bbenoist** [comment]
I can confirm, no more problem with your fix. Thanks!

**Comment by noahleigh** [comment]
I'm encountering the problem described by @bbenoist in the latest version (0.3.16). Pylint from the command line works fine, but Pylint in VSCode refuses to acknowledge it.

**Comment by DonJayamanne** [comment]
Sorry about this, please try the latest update, just fixed.

**Comment by noahleigh** [comment]
Still seeing the issue with 0.3.17 (vscode 1.2.1). What do you need to diagnose this?

**Comment by DonJayamanne** [comment]
Please could you look at the "python" output window and tell me what's in there.
How to get to the python output window?
- View -> Toggle Output
- From the dropdown list select "Python"   

Finally where have you placed your .pylintrc file (is it in the root directory of the project folder, i.e. workspace root)?

**Comment by noahleigh** [comment]
Python view contents:

```
##########Linting Output - pylint##########************* Module dslib.validation_utils.constraints
426,26,error,E1101:Module 'numpy' has no 'in1d' member
501,25,error,E1101:Module 'numpy' has no 'logical_or' member
503,26,error,E1101:Module 'numpy' has no 'logical_not' member
590,38,error,E1101:Module 'numpy' has no 'logical_or' member
592,38,error,E1101:Module 'numpy' has no 'logical_or' member
645,15,error,E1101:Module 'numpy' has no 'diff' member
645,32,error,E1101:Module 'numpy' has no 'diff' member
654,27,error,E1101:Module 'numpy' has no 'logical_or' member
766,26,error,E1101:Module 'numpy' has no 'logical_not' member
816,32,error,E1101:Module 'numpy' has no 'unique' member
869,30,error,E1101:Module 'numpy' has no 'logical_not' member
869,45,error,E1101:Module 'numpy' has no 'ediff1d' member
1025,26,error,E1101:Module 'numpy' has no 'logical_not' member
No config file found, using default configuration
```

And yes, my .pylintrc file is in the root of my project directory. Obviously pylint isn't seeing it in vscode for some reason, but the command line works fine.

**Comment by stevenmwade** [comment]
I am also having this problem on v0.5.6 and VSCode v1.8.1.

**Comment by noahleigh** [comment]
In my instance, turns out `.pylintrc` was actually within the main *subfolder* in my repo/workspace, which is why it wasn't being found by the linter. It was a side effect of the project being created in Eclipse, which produced an extra layer of folder depth.

The linter is working as expected now.

**Comment by DonJayamanne** [comment]
@noahleigh
Please provide the directory structure, the work space directory, location of pylint and the file being linted

**Comment by noahleigh** [comment]
**Not Working**
```
%USERPROFILE%/Documents/git/workspace_root/
├──.git/
├──.vscode/
└── project_root/
    ├── module_dir/
    │   ├── __init__.py
    │   └── module.py
    └── .pylintrc
```

**Working**
```
%USERPROFILE%/Documents/git/workspace_root/
├──.git/
├──.vscode/
├── project_root/
│   └── module_dir/
│       ├── __init__.py
│       └── module.py
└── .pylintrc
```

**Comment by DonJayamanne** [comment]
Yes that makes sense, missed you previous comment. Thanks

**Comment by BigstickCarpet** [comment]
I am still having this issue.  However, I've been able to workaround it by using the `python.linting.pylintArgs` setting to explicitly point to the `.pylintrc` file

```json
  "python.linting.pylintArgs": [
    "--rcfile",
    "${workspaceFolder}\\.pylintrc"
  ],
```

**Comment by DonJayamanne** [comment]
This issue has been closed, also please report issues on the Microsoft branch.
