### ISSUE TITLE
Debugging does not work in virtualenv on mac

### ISSUE THREAD

**Issue by tjhgit** [DonJayamanne/pythonVSCode#158]
The debugger always ends with the following error:
RuntimeError, T method already has a docstring

**Comment by DonJayamanne** [comment]
Hi, please could you ensure you have configured the launch.json file as per the [wiki](https://github.com/DonJayamanne/pythonVSCode/wiki/Python-Path-and-Version).
Details on the following issue also might help #148.

If your problem still persists, please could you try dbugging something as simple as the following and let me know what happens:
```python
value = 1 + 2
print value
```

**Comment by DonJayamanne** [comment]
Hi @tjhgit , you might want to try the following approach:

1. Clear all of the custom python paths in the settings.json (leave it to their defaults) and close VS Code
2. Open your terminal (command) window and activate the relevant python environment
```
(venv) ter@minal:~$ code project_folder/
```
3. Next, launch VS Code from that terminal (command window) session

Now, VS Code will inherit the environment variables (settings) configured for that particular Python Virtual Environment and everything should work as expected.
Please let me know how this goes.

Finally if this does work, then please let me know whether you prefer this approach or whether you would rather have some way of activating the environment from within VS Code & not have to configure the settings in settings.json. 
If this is preferred, how often do you see your selves changing the python environment? Is this only done when you open a project or do you have multiple environments for each project?

**Comment by symbioticKid** [comment]
Tried the above, but doesn't seem to be working for windows. 

launch.json below
`{
            "name": "Python",
            "type": "python",
            "request": "launch",
            "stopOnEntry": true,
            "program": "${file}",
            "debugOptions": [
                "WaitOnAbnormalExit",
                "WaitOnNormalExit",
                "RedirectOutput"
            ]
        }`

Python output is saying - No config file found, using default configuration

**Comment by tjhgit** [comment]
So here is my settings.json:
// Place your settings in this file to overwrite the default settings
{
    "python.formatting.provider": "autopep8",
    "python.linting.enabled": true
}
and here my workspace setting.json
// Place your settings in this file to overwrite the default settings
{
    "python.formatting.provider": "autopep8",
    "python.linting.enabled": true
}

When I debug python code that does not use numpy or pandas it works. However for the latter the debugger always jumps into function_base.py into this line:
            add_docstring(getattr(new, doc[0]), doc[1].strip())
and the debugging console reports:
RuntimeError, T method already has a doctoring

**Comment by DonJayamanne** [comment]
Hi, you can ignore these exceptions by modifying the launch.json file. 
Under the exceptions section ignore "RuntimeError".
I am looking for a more permanent solution.

**Comment by DonJayamanne** [comment]
Hi @tjhgit, please could you pasre the contents of your launch.json file?
Please ensure you have configured the path to the python executable (found in your virtual env) I the setting "pythonPath".
That should fix it.

**Comment by tjhgit** [comment]
Hi ,

I do not have an exception section. What exactly should I add to launch.json?

The python path is correct. Here is the contents of the file:
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Python",
            "type": "python",
            "request": "launch",
            "pythonPath":"/Users/thomas_mac/.virtualenvs/scientific/bin/python2.7",
            "stopOnEntry": true,
            "program": "${file}",
            "debugOptions": [
                "WaitOnAbnormalExit",
                "WaitOnNormalExit",
                "RedirectOutput"
            ]
        },
        {
            "name": "Python Console App",
            "type": "python",
            "request": "launch",
            "pythonPath":"/Users/thomas_mac/.virtualenvs/scientific/bin/python2.7",
            "stopOnEntry": true,
            "program": "${file}",
            "externalConsole": true,
            "debugOptions": [
                "WaitOnAbnormalExit",
                "WaitOnNormalExit"
            ]
        },
        {
            "name": "Django",
            "type": "python",
            "request": "launch",
            "stopOnEntry": true,
            "program": "${workspaceRoot}/manage.py",
            "args": [
                "runserver",
                "--noreload"
            ],
            "debugOptions": [
                "WaitOnAbnormalExit",
                "WaitOnNormalExit",
                "RedirectOutput",
                "DjangoDebugging"
            ]
        },
        {
            "name": "Watson",
            "type": "python",
            "request": "launch",
            "stopOnEntry": true,
            "program": "${workspaceRoot}/console.py",
            "args": [
                "dev",
                "runserver",
                "--noreload=True"
            ],
            "debugOptions": [
                "WaitOnAbnormalExit",
                "WaitOnNormalExit",
                "RedirectOutput"
            ]
        }
    ]
}

**Comment by DonJayamanne** [comment]
Here you go, add the following (only change is the addition of the exceptionHandling setting):

```json
{
"name": "Python",
"type": "python",
"request": "launch",
"pythonPath":"/Users/thomas_mac/.virtualenvs/scientific/bin/python2.7",
"stopOnEntry": true,
"program": "${file}",
"exceptionHandling": { "unhandled" : [], "ignore": ["RuntimeError"], "always" : [] },
"debugOptions": [
"WaitOnAbnormalExit",
"WaitOnNormalExit",
"RedirectOutput"
]
},
```

**Comment by tjhgit** [comment]
Unfortunately even after adding the line "exceptionHandling" to launch.json and restarting code, i still get the runtime errors as before when using numpy or pandas.

**Comment by DonJayamanne** [comment]
That's very odd, i'm testing this on a Mac and its working without any issues.

**Comment by DonJayamanne** [comment]
Hi, I'll close this as it is a duplicate of #107

**Comment by DonJayamanne** [comment]
Hi Everyone, I believe I have identified the issue and the fix will be available in the next build.
I believe this is related to issue #159
