### ISSUE TITLE
formatting with autopepe8 or yapf  failed

### ISSUE THREAD

**Issue by zhouchengcom** [DonJayamanne/pythonVSCode#181]
When I format any python file , pyhton console output "Error: Invalid patch string: @@ -*,* +*,* @@"

settings.json like this

"python.formatting.autopep8Path":"C:/Python27_32/Scripts/autopep8.exe  --max-line-length=160",

vscode python version:0.3.11

**Comment by DonJayamanne** [comment]
Will look into this asap

**Comment by DonJayamanne** [comment]
@zhouchengcom , I can't replicate this.
Please could you send me the code that you're trying to format.
If you cannot send me that code, could you try to create some code that does cause the formatting to fall over. Thanks

**Comment by zhouchengcom** [comment]
I print format cmd and result
C:/Python27_32/Scripts/autopep8.exe --diff "d:\docker_locustio\lic\const.py"   
_this.outputChannel.appendLine(data[1]);
output like this

--- original/d:\docker_locustio\lic\const.py
+++ fixed/d:\docker_locustio\lic\const.py
@@ -1 +1 @@
-CELERY_QUEUE_NAME="CELERY_QUEUE"
+CELERY_QUEUE_NAME = "CELERY_QUEUE"

and then error  output like this Error: Invalid patch string: @@ -1 +1 @@

**Comment by DonJayamanne** [comment]
Please could you provide the code that is formatted. As mentioned it works as expected at my end.
I have only tried it with the following two lines of text
```python
CELERY_QUEUE_NAME="CELERY_QUEUE"
<empty line>   
```

**Comment by zhouchengcom** [comment]
My code is the same as yours

**Comment by DonJayamanne** [comment]
Hmm, leave it with me for around one or two days. I'm in the middle of a refactor in the manner in which libraries such as  pylint, autopep8, are being utilized.
I should be in a position to push an update out soon.

The only change would be:
- Arguments such as --max-line-length would have to be specified separately as follows:
```json
"python.formatting.autopep8Path":"C:/Python27_32/Scripts/autopep8.exe",
"python.formatting.autopep8Args": ["--max-line-length=160"],
```

**Comment by zhouchengcom** [comment]
ok thanks

**Comment by DonJayamanne** [comment]
sorry about that. But as mentioned I am unable to replicate it.
And i'm hoping this won't be an issue with the new update.

**Comment by Hugh-wong** [comment]
Hey, I got this message same as the *zhouchengcom* did, maybe the `vs code version` is the reason ?

Currently I am using the vs code `1.2.1` on windows 10,  python version is `0.3.11`

**Comment by DonJayamanne** [comment]
@Hugh-wong, I will look into this once again tomorrow.

**Comment by DonJayamanne** [comment]
@Hugh-wong @zhouchengcom , a new update has been published, please could you test it out and let me know know this goes.

**Comment by DonJayamanne** [comment]
Oops closed by accident

**Comment by zhouchengcom** [comment]
I know why because process output newline is “\r\n” but diff split line is use "\n"

**Comment by DonJayamanne** [comment]
Checking this out now, thanks for the find.

**Comment by DonJayamanne** [comment]
Looks like a bug in the library itself, i'm submitted a pull requested and temporarily patched the file.
I'll release a new version with this patch soon.

**Comment by LRPalacios** [comment]
I am having an issue with the formatter too it shows on the python output: 

```
Formatting with autopep8 failed. Please install the formatter or turn it off.

Error: Invalid patch mode "\" in:  No newline at end of file
```

My visual studio code version is 1.2.1,
and i have installed autopep8 in the active virtual env

**Comment by LRPalacios** [comment]
I can confirm is related to the end of line secuence, when i use LF it works ok, but if i use CRLF it throws the error.

Windows 10
VS Code: 1.2.1
PythonVsCode: 0.3.14

**Comment by DonJayamanne** [comment]
@LRPalacios , I have identified the cause and fixed it. The next build will contain the fix.
The issue is due to the way python generates diffs form text (http://bugs.python.org/issue2142)

**Comment by LRPalacios** [comment]
Ok, Thanks @DonJayamanne i will wait for next build

**Comment by DonJayamanne** [comment]
Hi everyone, a new build has been released and should resolve this issue.

**Comment by zhouchengcom** [comment]
great work

**Comment by DonJayamanne** [comment]
Please could you confirm it is now working, so i could close this issue. Thanks

**Comment by LRPalacios** [comment]
Its working great for me now

**Comment by troxellophilus** [comment]
I am still seeing the issue, unfortunately.

Output after pydocstyle linting output:
```
Formatting with yapf failed.
Error: Invalid patch string: 
```

settings.json:
```
{
    "python.linting.pydocstyleEnabled": true,
    "python.formatting.provider": "yapf",
    "python.formatting.formatOnSave": true
}
```

Windows 7
VSCode 1.2.1
PythonVSCode 0.3.16

**Comment by DonJayamanne** [comment]
Please could you update to the latest version and try again. If it still fails then please uploaded the code toy are trying to format.

**Comment by Hugh-wong** [comment]
@DonJayamanne It's OK now on version `0.3.16`,  thanks for the work!

**Comment by DonJayamanne** [comment]
Unfortunately, there is another related bug. #188
