### ISSUE TITLE
Not able to get intellisense

### ISSUE THREAD

**Issue by DaveyD** [DonJayamanne/pythonVSCode#30]
Hi, I just installed your extension, but I am not seeming to get any intellisense
Is there any settings that has to be set/changed before getting this to work?

- I am running VScode 0.10.3
- I have python3.5 installed and it's in my path variable
- Windows 10 pro 64 bit

Thanks,
David

**Comment by DonJayamanne** [comment]
Sorry for the delay, been away the whole of last week.
I've been using Windows 10 for my work and it works. Please ensure you have Python in your current path or configure the path to the python executable in your user settings file as follows:

FYI - The location of the python executable may vary on your pc.
```json
{
    "python.pythonPath": "C:/Users/<UserName>/AppData/Local/Programs/Python/Python35-32/python.exe"
}
```

Further documentation can be found here: https://github.com/DonJayamanne/pythonVSCode/wiki/Python-Version

**Comment by DaveyD** [comment]
Hi, thanks for the reply
I still can't get this to work
I added the following to both my user settings and workspace settings:
`"python.pythonPath": "C:/Python/Python27/python.exe"`
(I also tried with python 3.5)
But still nothing happens.
E.g., I wrote `import os`, I typed `os.` but nothing came up

Anything else I can try??
Please let me know,
Thanks!

**Comment by DonJayamanne** [comment]
Very odd, let me have a look tonight. Sorry for the wait.

**Comment by DaveyD** [comment]
Ok, thanks - I appreciate it
I am so interested in getting this to work.... I've been working on this all day! :) 

Thanks,
David

**Comment by DonJayamanne** [comment]
Hi, I will be releasing a new version later today or early tomorrow morning, hopefully that will resolve the issue, if not it will show us what is going on. As I have added some additional logging to a key area that I had missed.

**Comment by DaveyD** [comment]
Ok, sounds great! Looking forward
Thanks a lot!

P.S. How are updates installed?

**Comment by DonJayamanne** [comment]
Unfortunately, you need to reinstall the extension from vscode. Hopefully microsoft will provide a better way of notifying people of available updates.

**Comment by DonJayamanne** [comment]
However you will not lose any thing when you reinstall the extension.

**Comment by DaveyD** [comment]
Ok, awesome
Thanks!

**Comment by DavidA2014** [comment]
Hi Don and David
I'm also trying out Don's Python plugin and haven't managed to make Intellisense work. I'm running VS Code 0.10.8 on Win 8.1. I don't know how to find out which version of the Python plugin I am using but I installed it in the last couple of days.

I have tried these Python paths:

`"python.pythonPath": "C:/Kivy-1.9.0-py3.4-win32-x64/Python34/python.exe"`
`"python.pythonPath": "C:/Python27/python.exe"`

which are both valid.  Then tested Intellisense by typing:

```
import sys
sys.
```

but no completions come up.

I'd be please to do more testing if you would like.

Best regards

David

**Comment by DaveyD** [comment]
@DavidA2014 - Good to know I'm not the only one with this issue!

@DonJayamanne - Looking forward for the update!!!

**Comment by the-efi** [comment]
Testing it on OS X, no Intellisense whatsoever. 

If I press Ctrl-Space, it shows either "Loading..." or "No  suggestions." and then nothing happens.

**Comment by DonJayamanne** [comment]
Hi, Please could you provide some more information. Have you configured your settings as per the documentation, what version of python are you using finally what did does code look like?

**Comment by the-efi** [comment]
I'm using Python 2.7.10 on OS X 10.11.3. Code is 0.10.9.

My work folder has .vscode/settings.json as follows:

```
{
    "python.pythonPath": "/Users/me/Envs/myvirtualenvenv/bin/python"
}  
```

Today some of intellisense seems to work.

Still, when I stand on

```
def find_existing(company, employee_id):
    dao = EmployeeDAO(company)
```

And perform "Go to definition" over EmployeeDAO, it takes me to the beginning of the file where it says:

```
from databases.something.something_else import EmployeeDAO
``` 

and not to the definition in file something_else.py residing in databases/something folder. (databases folder is a sibling of .vscode; sometimes it will reside in src/ folder, but not in this case)

**Comment by DavidA2014** [comment]
Hi Don
Seems a few of us are having trouble getting Intellisense to work. How can we help you with this? Would it be better to have separate issues for each person reporting the problem? Do you need more information?
One thing that may help is for you to suggest a test case, i.e. a sequence of typing that should prompt Intellisense to do something, then we can rule out user error.
Thanks
David

**Comment by DonJayamanne** [comment]
Sorry about this. I am in the process of updating the extension with some more logging. I will release it this week with further instructions. I am truly sorry about the delay and this bug. The worst case would be to get someone to help me debug and identify the big.

**Comment by DavidA2014** [comment]
Thanks for your reply. No need for an apology. I'm very grateful for the effort you are putting into this extension.

**Comment by DaveyD** [comment]
Hi Don, I'm right there with David (the other one :) )
I can't wait for this to work!
Thanks for attending to this issue and further developing!
Looking forward.....

**Comment by DonJayamanne** [comment]
Hi guys, I've released a new version with some logging.
Here's what you need to do:

1. Install the latest version (duh)
2. Open VS Code
3. Open a Python project folder
4. Configure the user or workspace settings (either one)
You need to turn on some custom logging as follows:
`
"python.devOptions": ["DEBUG"]
`
This basically tells the extension to log extra stuff to a custom output log named "PythonExtLog"
5. Restart VS Code (remember - you must restart it)
6. Open the Python project folder
7. Open a python file
8. Go into the menu and view the custom output "Toggle Output" and view the output for "PythonExtLog"
9. Have a look at the output in here.
Hopefully this will shed some more light into what is going on

If this doesn't work, i'll need someones' help debugging this (that's easy).
Hopefully we can fix this asap.

**Comment by DavidA2014** [comment]
Hi Don, thanks for the release and instructions. I believe I have followed them.

In Toggle Output > PythonExtLog I see repeatedly:

```
child_process.spawn in jediProxy
Value of pythonSettings.pythonPath is :C:/Python34/python.exe
```

Nothing appears if I type:

```
import sys
sys.
```

In Toggle Output > Python I see:

```
'pylint' is not recognized as an internal or external command,
operable program or batch file.
```

I hope that helps.

David

**Comment by DonJayamanne** [comment]
Hmm, not what I was expecting. Please could you do one of the following:
1. Either install pylint    
2. Or disable linting as follows:   
```json
"python.linting.pylintEnabled": false
```
3. Restart VSCode and let me know what you get this time

**Comment by DavidA2014** [comment]
I disabled linting as you suggested. Toggle Output > Python is now clear.  

No other observed changes. I still see, in Toggle Output > PythonExtLog :

```
child_process.spawn in jediProxy
Value of pythonSettings.pythonPath is :C:/Python34/python.exe
```

and Intellisense doesn't work.

**Comment by DonJayamanne** [comment]
That's odd, very odd.
Please could you create a new folder and place one file in there named test.py.
Open this folder using VSCode.
Open the test.py file and type the following in there:
```python
import sys
sys.
```

Wait for a few seconds and then remove the "." after sys and type the "." again.
I.e. try to re-activate the auto complete by removing everything and typing it again

**Comment by DavidA2014** [comment]
You may be relieved to hear that that test works fine :-)

I don't know what that means for my usual project folder, where it's not working.

**Comment by DonJayamanne** [comment]
Can you describe your project folder?    
Do you have lots of files, if so how many, 10, 20, 50 or 100?
I guess, one approach is to try to identify the file that causes autocomplete to take too long.
There must be a file in the folder that is causing auto complete to either fall over silently (unlikely as nothing is logged) or it is just taking too long.

**Comment by DonJayamanne** [comment]
And thanks a lot for your help

**Comment by DavidA2014** [comment]
My project folder, which I open in VS Code has 2700 files.  The Python code is in one subfolder, containing ~20 files.  If I open just that Python folder then Intellisense works.

Sorry if I have wasted your time.

**Comment by DonJayamanne** [comment]
Oh no you haven't wasted my time at all. Its all a learning excercise. 
However 2700 files is indeed quite large.
Anyways, thanks for your help.

**Comment by DavidA2014** [comment]
Thanks for your help too.

**Comment by DonJayamanne** [comment]
Team work

**Comment by DaveyD** [comment]
Hi Don, thanks for the update!
However, intellisense is stll not working by me.... but I can't through the first step of debugging!

1. I uninstalled the previous version
2. Installed new version `0.3.1`
3. Added the following line into my local settings.json file: `"python.devOptions": ["DEBUG"]`
4. Closed VScode and restarted
5. Opened my `.py` file
6. Toggled output window - but I dont see anything. I dont see any option for `PythonExtLog`

What am I missing?
Thanks,
David

**Comment by DonJayamanne** [comment]
Do you see the other out put Windows, git , task, python? From that drop down list please select pythonextlog.

**Comment by DonJayamanne** [comment]
Please could you also create a .py  file in an empty directory and open that one. I.e. Start with and empty work space.

**Comment by DaveyD** [comment]
Hi Don, no I dont see anything else
Under the View menu, I only see 'Toggle output'
Am I looking in the right place?
(P.S. I dont have any debuggers set up - I've never done that)

Thanks,
David

**Comment by DaveyD** [comment]
I just created a new folder on my desktop, and created a new file `tes.py` inside it
I added the following lines to my settings:
```
{
	"python.pythonPath": "C:/Python/Python35/python.exe",
	"python.devOptions": ["DEBUG"]
}
```

I started writing some code, but no intellisense...
Anything else that I'm missing?

**Comment by the-efi** [comment]
```
child_process.spawn in jediProxy
Value of pythonSettings.pythonPath is :/Users/me/Envs/myenv/bin/python
---------------------------
stdout jediProxy
Error (stdout) Unexpected end of input
```

On the top, there's a red banner saying "There was an error in the python extension. Error Unexpected end of input".

**Comment by the-efi** [comment]
More error dumps:
```

stderr jediProxy
Error (stderr) Traceback (most recent call last):
  File "completion.py", line 309, in watch
    self._process_request(self._input.readline())
  File "completion.py", line 300, in _process_request
    request.get('prmex', '')))
  File "completion.py", line 136, in _serialize_completions
    completions = script.completions()
  File "/Users/me/.vscode/extensions/donjayamanne.python-0.3.1/pythonFiles/jedi/api/__init__.py", line 192, in completions
    completion_names = get_completions(user_stmt, b)
  File "/Users/me/.vscode/extensions/donjayamanne.python-0.3.1/pythonFiles/jedi/api/__init__.py", line 178, in get_completions
    completion_names += self._simple_complete(path, dot, like)
  File "/Users/me/.vscode/extensions/donjayamanne.python-0.3.1/pythonFiles/jedi/api/__init__.py", line 254, in _simple_complete
    scopes = list(self._prepare_goto(path, True))
  File "/Users/me/.vscode/extensions/donjayamanne.python-0.3.1/pythonFiles/jedi/api/__init__.py", line 298, in _prepare_goto
    scopes = self._evaluator.eval_element(eval_stmt)
  File "/Users/me/.vscode/extensions/donjayamanne.python-0.3.1/pythonFiles/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/Users/me/.vscode/extensions/donjayamanne.python-0.3.1/pythonFiles/jedi/evaluate/__init__.py", line 169, in eval_element
    return self._eval_atom(element)
  File "/Users/me/.vscode/extensions/donjayamanne.python-0.3.1/pythonFiles/jedi/evaluate/__init__.py", line 230, in _eval_atom
    return self.find_types(scope, atom, stmt.start_pos, search_global=True)
  File "/Users/me/.vscode/extensions/donjayamanne.python-0.3.1/pythonFiles/jedi/evaluate/__init__.py", line 120, in find_types
    return f.find(scopes, search_global)
  File "/Users/me/.vscode/extensions/donjayamanne.python-0.3.1/pythonFiles/jedi/debug.py", line 52, in wrapper
    result = func(*args, **kwargs)
  File "/Users/me/.vscode/extensions/donjayamanne.python-0.3.1/pythonFiles/jedi/evaluate/finder.py", line 87, in find
    types = self._names_to_types(names, search_global)
  File "/Users/me/.vscode/extensions/donjayamanne.python-0.3.1/pythonFiles/jedi/evaluate/finder.py", line 233, in _names_to_types
    new_types = _name_to_types(self._evaluator, name, self.scope)
  File "/Users/me/.vscode/extensions/donjayamanne.python-0.3.1/pythonFiles/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/Users/me/.vscode/extensions/donjayamanne.python-0.3.1/pythonFiles/jedi/evaluate/finder.py", line 278, in _name_to_types
    types += _remove_statements(evaluator, typ, name)
  File "/Users/me/.vscode/extensions/donjayamanne.python-0.3.1/pythonFiles/jedi/evaluate/finder.py", line 323, in _remove_statements
    types += evaluator.eval_statement(stmt, seek_name=name)
  File "/Users/me/.vscode/extensions/donjayamanne.python-0.3.1/pythonFiles/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/Users/me/.vscode/extensions/donjayamanne.python-0.3.1/pythonFiles/jedi/evaluate/recursion.py", line 23, in run
    result = func(evaluator, stmt, *args, **kwargs)
  File "/Users/me/.vscode/extensions/donjayamanne.python-0.3.1/pythonFiles/jedi/debug.py", line 52, in wrapper
    result = func(*args, **kwargs)
  File "/Users/me/.vscode/extensions/donjayamanne.python-0.3.1/pythonFiles/jedi/evaluate/__init__.py", line 135, in eval_statement
    types = self.eval_element(stmt.get_rhs())
  File "/Users/me/.vscode/extensions/donjayamanne.python-0.3.1/pythonFiles/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/Users/me/.vscode/extensions/donjayamanne.python-0.3.1/pythonFiles/jedi/evaluate/__init__.py", line 187, in eval_element
    types = self.eval_trailer(types, trailer)
  File "/Users/me/.vscode/extensions/donjayamanne.python-0.3.1/pythonFiles/jedi/evaluate/__init__.py", line 259, in eval_trailer
    new_types += self.execute(typ, node, trailer)
  File "/Users/me/.vscode/extensions/donjayamanne.python-0.3.1/pythonFiles/jedi/debug.py", line 52, in wrapper
    result = func(*args, **kwargs)
  File "/Users/me/.vscode/extensions/donjayamanne.python-0.3.1/pythonFiles/jedi/evaluate/__init__.py", line 299, in execute
    types = func(self, arguments)
  File "/Users/me/.vscode/extensions/donjayamanne.python-0.3.1/pythonFiles/jedi/_compatibility.py", line 124, in <lambda>
    return lambda *args, **kwargs: self.func(obj, *args, **kwargs)
  File "/Users/me/.vscode/extensions/donjayamanne.python-0.3.1/pythonFiles/jedi/evaluate/representation.py", line 560, in py__call__
    return FunctionExecution(evaluator, self, params).get_return_types()
  File "/Users/me/.vscode/extensions/donjayamanne.python-0.3.1/pythonFiles/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/Users/me/.vscode/extensions/donjayamanne.python-0.3.1/pythonFiles/jedi/evaluate/recursion.py", line 100, in run
    result = func(execution, **kwargs)
  File "/Users/me/.vscode/extensions/donjayamanne.python-0.3.1/pythonFiles/jedi/evaluate/representation.py", line 624, in get_return_types
    types += self._evaluator.eval_element(r.children[1])
  File "/Users/me/.vscode/extensions/donjayamanne.python-0.3.1/pythonFiles/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/Users/me/.vscode/extensions/donjayamanne.python-0.3.1/pythonFiles/jedi/evaluate/__init__.py", line 187, in eval_element
    types = self.eval_trailer(types, trailer)
  File "/Users/me/.vscode/extensions/donjayamanne.python-0.3.1/pythonFiles/jedi/evaluate/__init__.py", line 259, in eval_trailer
    new_types += self.execute(typ, node, trailer)
  File "/Users/me/.vscode/extensions/donjayamanne.python-0.3.1/pythonFiles/jedi/debug.py", line 52, in wrapper
    result = func(*args, **kwargs)
  File "/Users/me/.vscode/extensions/donjayamanne.python-0.3.1/pythonFiles/jedi/evaluate/__init__.py", line 299, in execute
    types = func(self, arguments)
  File "/Users/me/.vscode/extensions/donjayamanne.python-0.3.1/pythonFiles/jedi/_compatibility.py", line 124, in <lambda>
    return lambda *args, **kwargs: self.func(obj, *args, **kwargs)
  File "/Users/me/.vscode/extensions/donjayamanne.python-0.3.1/pythonFiles/jedi/evaluate/representation.py", line 560, in py__call__
    return FunctionExecution(evaluator, self, params).get_return_types()
  File "/Users/me/.vscode/extensions/donjayamanne.python-0.3.1/pythonFiles/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/Users/me/.vscode/extensions/donjayamanne.python-0.3.1/pythonFiles/jedi/evaluate/recursion.py", line 100, in run
    result = func(execution, **kwargs)
  File "/Users/me/.vscode/extensions/donjayamanne.python-0.3.1/pythonFiles/jedi/evaluate/representation.py", line 624, in get_return_types
    types += self._evaluator.eval_element(r.children[1])
  File "/Users/me/.vscode/extensions/donjayamanne.python-0.3.1/pythonFiles/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/Users/me/.vscode/extensions/donjayamanne.python-0.3.1/pythonFiles/jedi/evaluate/__init__.py", line 169, in eval_element
    return self._eval_atom(element)
  File "/Users/me/.vscode/extensions/donjayamanne.python-0.3.1/pythonFiles/jedi/evaluate/__init__.py", line 230, in _eval_atom
    return self.find_types(scope, atom, stmt.start_pos, search_global=True)
  File "/Users/me/.vscode/extensions/donjayamanne.python-0.3.1/pythonFiles/jedi/evaluate/__init__.py", line 120, in find_types
    return f.find(scopes, search_global)
  File "/Users/me/.vscode/extensions/donjayamanne.python-0.3.1/pythonFiles/jedi/debug.py", line 52, in wrapper
    result = func(*args, **kwargs)
  File "/Users/me/.vscode/extensions/donjayamanne.python-0.3.1/pythonFiles/jedi/evaluate/finder.py", line 87, in find
    types = self._names_to_types(names, search_global)
  File "/Users/me/.vscode/extensions/donjayamanne.python-0.3.1/pythonFiles/jedi/evaluate/finder.py", line 233, in _names_to_types
    new_types = _name_to_types(self._evaluator, name, self.scope)
  File "/Users/me/.vscode/extensions/don
---------------------------
stderr jediProxy
Error (stderr) jayamanne.python-0.3.1/pythonFiles/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/Users/me/.vscode/extensions/donjayamanne.python-0.3.1/pythonFiles/jedi/evaluate/finder.py", line 278, in _name_to_types
    types += _remove_statements(evaluator, typ, name)
  File "/Users/me/.vscode/extensions/donjayamanne.python-0.3.1/pythonFiles/jedi/evaluate/finder.py", line 323, in _remove_statements
    types += evaluator.eval_statement(stmt, seek_name=name)
  File "/Users/me/.vscode/extensions/donjayamanne.python-0.3.1/pythonFiles/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/Users/me/.vscode/extensions/donjayamanne.python-0.3.1/pythonFiles/jedi/evaluate/recursion.py", line 23, in run
    result = func(evaluator, stmt, *args, **kwargs)
  File "/Users/me/.vscode/extensions/donjayamanne.python-0.3.1/pythonFiles/jedi/debug.py", line 52, in wrapper
    result = func(*args, **kwargs)
  File "/Users/me/.vscode/extensions/donjayamanne.python-0.3.1/pythonFiles/jedi/evaluate/__init__.py", line 135, in eval_statement
    types = self.eval_element(stmt.get_rhs())
  File "/Users/me/.vscode/extensions/donjayamanne.python-0.3.1/pythonFiles/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/Users/me/.vscode/extensions/donjayamanne.python-0.3.1/pythonFiles/jedi/evaluate/__init__.py", line 187, in eval_element
    types = self.eval_trailer(types, trailer)
  File "/Users/me/.vscode/extensions/donjayamanne.python-0.3.1/pythonFiles/jedi/evaluate/__init__.py", line 259, in eval_trailer
    new_types += self.execute(typ, node, trailer)
  File "/Users/me/.vscode/extensions/donjayamanne.python-0.3.1/pythonFiles/jedi/debug.py", line 52, in wrapper
    result = func(*args, **kwargs)
  File "/Users/me/.vscode/extensions/donjayamanne.python-0.3.1/pythonFiles/jedi/evaluate/__init__.py", line 299, in execute
    types = func(self, arguments)
  File "/Users/me/.vscode/extensions/donjayamanne.python-0.3.1/pythonFiles/jedi/evaluate/representation.py", line 364, in py__call__
    return Function.py__call__(self, evaluator, params)
  File "/Users/me/.vscode/extensions/donjayamanne.python-0.3.1/pythonFiles/jedi/_compatibility.py", line 122, in <lambda>
    return lambda *args, **kwargs: self.func(*args, **kwargs)
  File "/Users/me/.vscode/extensions/donjayamanne.python-0.3.1/pythonFiles/jedi/evaluate/representation.py", line 560, in py__call__
    return FunctionExecution(evaluator, self, params).get_return_types()
  File "/Users/me/.vscode/extensions/donjayamanne.python-0.3.1/pythonFiles/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/Users/me/.vscode/extensions/donjayamanne.python-0.3.1/pythonFiles/jedi/evaluate/recursion.py", line 100, in run
    result = func(execution, **kwargs)
  File "/Users/me/.vscode/extensions/donjayamanne.python-0.3.1/pythonFiles/jedi/evaluate/representation.py", line 624, in get_return_types
    types += self._evaluator.eval_element(r.children[1])
  File "/Users/me/.vscode/extensions/donjayamanne.python-0.3.1/pythonFiles/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/Users/me/.vscode/extensions/donjayamanne.python-0.3.1/pythonFiles/jedi/evaluate/__init__.py", line 169, in eval_element
    return self._eval_atom(element)
  File "/Users/me/.vscode/extensions/donjayamanne.python-0.3.1/pythonFiles/jedi/evaluate/__init__.py", line 230, in _eval_atom
    return self.find_types(scope, atom, stmt.start_pos, search_global=True)
  File "/Users/me/.vscode/extensions/donjayamanne.python-0.3.1/pythonFiles/jedi/evaluate/__init__.py", line 120, in find_types
    return f.find(scopes, search_global)
  File "/Users/me/.vscode/extensions/donjayamanne.python-0.3.1/pythonFiles/jedi/debug.py", line 52, in wrapper
    result = func(*args, **kwargs)
  File "/Users/me/.vscode/extensions/donjayamanne.python-0.3.1/pythonFiles/jedi/evaluate/finder.py", line 87, in find
    types = self._names_to_types(names, search_global)
  File "/Users/me/.vscode/extensions/donjayamanne.python-0.3.1/pythonFiles/jedi/evaluate/finder.py", line 233, in _names_to_types
    new_types = _name_to_types(self._evaluator, name, self.scope)
  File "/Users/me/.vscode/extensions/donjayamanne.python-0.3.1/pythonFiles/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/Users/me/.vscode/extensions/donjayamanne.python-0.3.1/pythonFiles/jedi/evaluate/finder.py", line 278, in _name_to_types
    types += _remove_statements(evaluator, typ, name)
  File "/Users/me/.vscode/extensions/donjayamanne.python-0.3.1/pythonFiles/jedi/evaluate/finder.py", line 323, in _remove_statements
    types += evaluator.eval_statement(stmt, seek_name=name)
  File "/Users/me/.vscode/extensions/donjayamanne.python-0.3.1/pythonFiles/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/Users/me/.vscode/extensions/donjayamanne.python-0.3.1/pythonFiles/jedi/evaluate/recursion.py", line 23, in run
    result = func(evaluator, stmt, *args, **kwargs)
  File "/Users/me/.vscode/extensions/donjayamanne.python-0.3.1/pythonFiles/jedi/debug.py", line 52, in wrapper
    result = func(*args, **kwargs)
  File "/Users/me/.vscode/extensions/donjayamanne.python-0.3.1/pythonFiles/jedi/evaluate/__init__.py", line 135, in eval_statement
    types = self.eval_element(stmt.get_rhs())
  File "/Users/me/.vscode/extensions/donjayamanne.python-0.3.1/pythonFiles/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/Users/me/.vscode/extensions/donjayamanne.python-0.3.1/pythonFiles/jedi/evaluate/__init__.py", line 187, in eval_element
    types = self.eval_trailer(types, trailer)
  File "/Users/me/.vscode/extensions/donjayamanne.python-0.3.1/pythonFiles/jedi/evaluate/__init__.py", line 259, in eval_trailer
    new_types += self.execute(typ, node, trailer)
  File "/Users/me/.vscode/extensions/donjayamanne.python-0.3.1/pythonFiles/jedi/debug.py", line 52, in wrapper
    result = func(*args, **kwargs)
  File "/Users/me/.vscode/extensions/donjayamanne.python-0.3.1/pythonFiles/jedi/evaluate/__init__.py", line 299, in execute
    types = func(self, arguments)
  File "/Users/me/.vscode/extensions/donjayamanne.python-0.3.1/pythonFiles/jedi/evaluate/representation.py", line 364, in py__call__
    return Function.py__call__(self, evaluator, params)
  File "/Users/me/.vscode/extensions/donjayamanne.python-0.3.1/pythonFiles/jedi/_compatibility.py", line 122, in <lambda>
    return lambda *args, **kwargs: self.func(*args, **kwargs)
  File "/Users/me/.vscode/extensions/donjayamanne.python-0.3.1/pythonFiles/jedi/evaluate/representation.py", line 560, in py__call__
    return FunctionExecution(evaluator, self, params).get_return_types()
  File "/Users/me/.vscode/extensions/donjayamanne.python-0.3.1/pythonFiles/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/Users/me/.vscode/extensions/donjayamanne.python-0.3.1/pythonFiles/jedi/evaluate/recursion.py", line 100, in run
    result = func(execution, **kwargs)
  File "/Users/me/.vscode/extensions/donjayamanne.python-0.3.1/pythonFiles/jedi/evaluate/representation.py", line 624, in get_return_types
    types += self._evaluator.eval_element(r.children[1])
  File "/Users/me/.vscode/extensions/donjayamanne.python-0.3.1/pythonFiles/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/Users/me/.vscode/extensions/donjayamanne.python-0.3.1/pythonFiles/jedi/evaluate/__init__.py", line 169, in eval_element
    return self._eval_atom(element)
  File "/Users/me/.vscode/extensions/donjayamanne.python-0.3.1/pythonFiles/jedi/evaluate/__init__.py", line 230, in _eval_atom
    return self.find_types(scope, atom, stmt.start_pos, search_global=True)
  File "/Users/me/.vscode/extensions/donjayamanne.python-0.3.1/pythonFiles/jedi/evaluate/__init__.py", line 120, in find_types
    return f.find(scopes, search_global)
  File "/Users/me/.vscode/extensions/donjayamanne.python-0.3.1/pythonF
---------------------------
stderr jediProxy
Error (stderr) iles/jedi/debug.py", line 52, in wrapper
    result = func(*args, **kwargs)
  File "/Users/me/.vscode/extensions/donjayamanne.python-0.3.1/pythonFiles/jedi/evaluate/finder.py", line 87, in find
    types = self._names_to_types(names, search_global)
  File "/Users/me/.vscode/extensions/donjayamanne.python-0.3.1/pythonFiles/jedi/evaluate/finder.py", line 233, in _names_to_types
    new_types = _name_to_types(self._evaluator, name, self.scope)
  File "/Users/me/.vscode/extensions/donjayamanne.python-0.3.1/pythonFiles/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/Users/me/.vscode/extensions/donjayamanne.python-0.3.1/pythonFiles/jedi/evaluate/finder.py", line 278, in _name_to_types
    types += _remove_statements(evaluator, typ, name)
  File "/Users/me/.vscode/extensions/donjayamanne.python-0.3.1/pythonFiles/jedi/evaluate/finder.py", line 323, in _remove_statements
    types += evaluator.eval_statement(stmt, seek_name=name)
  File "/Users/me/.vscode/extensions/donjayamanne.python-0.3.1/pythonFiles/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/Users/me/.vscode/extensions/donjayamanne.python-0.3.1/pythonFiles/jedi/evaluate/recursion.py", line 23, in run
    result = func(evaluator, stmt, *args, **kwargs)
  File "/Users/me/.vscode/extensions/donjayamanne.python-0.3.1/pythonFiles/jedi/debug.py", line 52, in wrapper
    result = func(*args, **kwargs)
  File "/Users/me/.vscode/extensions/donjayamanne.python-0.3.1/pythonFiles/jedi/evaluate/__init__.py", line 135, in eval_statement
    types = self.eval_element(stmt.get_rhs())
  File "/Users/me/.vscode/extensions/donjayamanne.python-0.3.1/pythonFiles/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/Users/me/.vscode/extensions/donjayamanne.python-0.3.1/pythonFiles/jedi/evaluate/__init__.py", line 187, in eval_element
    types = self.eval_trailer(types, trailer)
  File "/Users/me/.vscode/extensions/donjayamanne.python-0.3.1/pythonFiles/jedi/evaluate/__init__.py", line 259, in eval_trailer
    new_types += self.execute(typ, node, trailer)
  File "/Users/me/.vscode/extensions/donjayamanne.python-0.3.1/pythonFiles/jedi/debug.py", line 52, in wrapper
    result = func(*args, **kwargs)
  File "/Users/me/.vscode/extensions/donjayamanne.python-0.3.1/pythonFiles/jedi/evaluate/__init__.py", line 299, in execute
    types = func(self, arguments)
  File "/Users/me/.vscode/extensions/donjayamanne.python-0.3.1/pythonFiles/jedi/evaluate/representation.py", line 364, in py__call__
    return Function.py__call__(self, evaluator, params)
  File "/Users/me/.vscode/extensions/donjayamanne.python-0.3.1/pythonFiles/jedi/_compatibility.py", line 122, in <lambda>
    return lambda *args, **kwargs: self.func(*args, **kwargs)
  File "/Users/me/.vscode/extensions/donjayamanne.python-0.3.1/pythonFiles/jedi/evaluate/representation.py", line 560, in py__call__
    return FunctionExecution(evaluator, self, params).get_return_types()
  File "/Users/me/.vscode/extensions/donjayamanne.python-0.3.1/pythonFiles/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/Users/me/.vscode/extensions/donjayamanne.python-0.3.1/pythonFiles/jedi/evaluate/recursion.py", line 100, in run
    result = func(execution, **kwargs)
  File "/Users/me/.vscode/extensions/donjayamanne.python-0.3.1/pythonFiles/jedi/evaluate/representation.py", line 624, in get_return_types
    types += self._evaluator.eval_element(r.children[1])
  File "/Users/me/.vscode/extensions/donjayamanne.python-0.3.1/pythonFiles/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/Users/me/.vscode/extensions/donjayamanne.python-0.3.1/pythonFiles/jedi/evaluate/__init__.py", line 187, in eval_element
    types = self.eval_trailer(types, trailer)
  File "/Users/me/.vscode/extensions/donjayamanne.python-0.3.1/pythonFiles/jedi/evaluate/__init__.py", line 267, in eval_trailer
    new_types += get(self, node)
  File "/Users/me/.vscode/extensions/donjayamanne.python-0.3.1/pythonFiles/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/Users/me/.vscode/extensions/donjayamanne.python-0.3.1/pythonFiles/jedi/evaluate/iterable.py", line 229, in get_index_types
    types += self.get_exact_index_types(index.obj)
  File "/Users/me/.vscode/extensions/donjayamanne.python-0.3.1/pythonFiles/jedi/evaluate/iterable.py", line 255, in get_exact_index_types
    return self._evaluator.eval_element(self._items()[mixed_index])
  File "/Users/me/.vscode/extensions/donjayamanne.python-0.3.1/pythonFiles/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/Users/me/.vscode/extensions/donjayamanne.python-0.3.1/pythonFiles/jedi/evaluate/__init__.py", line 169, in eval_element
    return self._eval_atom(element)
  File "/Users/me/.vscode/extensions/donjayamanne.python-0.3.1/pythonFiles/jedi/evaluate/__init__.py", line 230, in _eval_atom
    return self.find_types(scope, atom, stmt.start_pos, search_global=True)
  File "/Users/me/.vscode/extensions/donjayamanne.python-0.3.1/pythonFiles/jedi/evaluate/__init__.py", line 120, in find_types
    return f.find(scopes, search_global)
  File "/Users/me/.vscode/extensions/donjayamanne.python-0.3.1/pythonFiles/jedi/debug.py", line 52, in wrapper
    result = func(*args, **kwargs)
  File "/Users/me/.vscode/extensions/donjayamanne.python-0.3.1/pythonFiles/jedi/evaluate/finder.py", line 87, in find
    types = self._names_to_types(names, search_global)
  File "/Users/me/.vscode/extensions/donjayamanne.python-0.3.1/pythonFiles/jedi/evaluate/finder.py", line 233, in _names_to_types
    new_types = _name_to_types(self._evaluator, name, self.scope)
  File "/Users/me/.vscode/extensions/donjayamanne.python-0.3.1/pythonFiles/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/Users/me/.vscode/extensions/donjayamanne.python-0.3.1/pythonFiles/jedi/evaluate/finder.py", line 269, in _name_to_types
    for_types = iterable.get_iterator_types(for_types)
  File "/Users/me/.vscode/extensions/donjayamanne.python-0.3.1/pythonFiles/jedi/evaluate/iterable.py", line 418, in get_iterator_types
    result += it.iter_content()
  File "/Users/me/.vscode/extensions/donjayamanne.python-0.3.1/pythonFiles/jedi/evaluate/iterable.py", line 575, in iter_content
    module = self.var_args.get_parent_until()
  File "/Users/me/.vscode/extensions/donjayamanne.python-0.3.1/pythonFiles/jedi/evaluate/param.py", line 56, in get_parent_until
    return element.get_parent_until(*args, **kwargs)
  File "/Users/me/.vscode/extensions/donjayamanne.python-0.3.1/pythonFiles/jedi/_compatibility.py", line 124, in <lambda>
    return lambda *args, **kwargs: self.func(obj, *args, **kwargs)
  File "/Users/me/.vscode/extensions/donjayamanne.python-0.3.1/pythonFiles/jedi/parser/tree.py", line 123, in get_parent_until
    while scope.parent is not None:
AttributeError: 'ListComprehension' object has no attribute 'parent'
```

**Comment by DonJayamanne** [comment]
Hi, I am sorry but I am stumped. Not sure what is going on here?

Can you do me a simple favour? I am going for a shot in the dark 
Can you write a simple program to print a line to the console window and debug that?
I.e. Confirm that debuting works?

**Comment by DaveyD** [comment]
@Don - good news at my end
I opened the developer tools window and realized the problem! Your extension wasn't even starting because my VScode version was 10.3, and your extension required 10.8! (**I think this has to be made more clear**) - see [screenshot](
https://mega.nz/#!JhVCAbJI!YFwQircNkUrEnAdHjSJWUNaBiJZ0yh3VlEH6dYrrslc
)

I updated VScode to latest version, and now everything is working perfect!

Thank you!
David
P.S. I did mention in my original

**Comment by DonJayamanne** [comment]
Thanks for the info, I would have expected vs code to handle the minimum version.

**Comment by gglanzani** [comment]
@DonJayamanne In my case it still doesn't work. I've tried with small projects (two files). Pylint does work!

Not even same file completion for intellisense work :(

In the PythonExtLog I have nothing more than a bunch of 

```
---------------------------
child_process.spawn in jediProxy
Value of pythonSettings.pythonPath is :C:/Users/Giovanni/Envs/vscode/Scripts/python.exe
```

**Comment by the-efi** [comment]
Neither it works for me.

I also don't think that the ultimate test for this extension should be on new files in empty directories.

**Comment by DonJayamanne** [comment]
If there are errors raised by the completion.py file, then please raise those issues in the following git repo:
https://github.com/davidhalter/jedi

**Comment by gglanzani** [comment]
@DonJayamanne I will, but don't you find it strange that they are only present when pylint return with syntax errors?

**Comment by bmw95** [comment]
For anyone who is still getting issues, follow this [`blog`](http://www.anthonydebarros.com/2015/08/16/setting-up-python-in-windows-10/). I had installed Python but opted to have it add to my path automatically. I could start python in cmd, but no linters or intellisense in vscode, so I installed python to C:\Python35-32 instead of the default path, manually added python to the path environment, and it all worked fine. I use pylint so I did pip install pylint, but not sure whether that was really necessary or not.

**Comment by DonJayamanne** [comment]
@bmw95, that is the right way. Covered in the doco (wiki) too. Perhaps I need to present some  tips within the ui itself.

**Comment by bmw95** [comment]
Sure yeah that sounds like a good idea :). I'm still pretty new to Python and after resetting my system, forgot to manually set all the stuff instead of letting the installer do it.
