### ISSUE TITLE
Autodetect Python path in virtualenv

### ISSUE THREAD

**Issue by petr-k** [DonJayamanne/pythonVSCode#353]
It would be great if one could configure only a virtualenv directory path and the extensions would take care of the rest.

Currently, it is impossible to specify the path in a cross-platform way, since it differs between Windows and Linux (and possibly Mac).

**Comment by DonJayamanne** [comment]
@petr-k 
The only way you can specify a path in a cross platform way is to use relative paths.
And that is possible:

You do however need to prefix the path with the workspace root.
Assume your virtual environment is located in the project (workspace root) directory named ```'venv'```. Then you should be able to configure settings.json as follows:

```json
{
    "python.pythonPath": "${workspaceRoot}/venv"
}
```

Note: I say _**should**_. This is because everything except for debugging will work. The next version of VS Code will resolve this (next version of VS Code will be released some time tomorrow).

Hope this resolves your issue.

**Comment by petr-k** [comment]
Well I am aware about the workspace-relative option, which is a great feature, but the problem is that even within the env folder, the path to python executable differs between platforms. For example, it's something like `${workspaceRoot}/venv/Scripts/python.exe` on Windows, but `${workspaceRoot}/venv/bin/python` on Linux.

Or is your config fragment sample meant to imply that just the venv directory is enough and one does not need to specify the _python executable_ path?

**Comment by DonJayamanne** [comment]
Now, I see the problem, I'll modify the code so as to automatically use:  
- ```python.exe``` for windows  
- ```python``` for linux (i.e. everything other than windows)  

Will add this some time next week.
Currently working on the last bit to release the next version (tomorrow).  
But this should be easy

**Comment by DonJayamanne** [comment]
Good idea too

**Comment by niwox** [comment]
Any update for this ? I'm facing the same issue while configuring the python.pythonPath

**Comment by DonJayamanne** [comment]
what issue are you facing?

**Comment by niwox** [comment]
Adding 
```json
{
    "python.pythonPath": "${workspaceRoot}/venv"
}
```
or 
```json
{
    "python.pythonPath": "${workspaceRoot}/venv/Scripts/python.exe"
}
```
is not fixing the import warning (windows 7)

**Comment by DonJayamanne** [comment]
What is the warning

**Comment by niwox** [comment]
Autodetecting python and imports is not working. For example :
```
[pylint] C0111:Missing module docstring
[pylint] E0401:Unable to import 'flask'
```

**Comment by DonJayamanne** [comment]
@niwox that's a completely different issue from what @petr-k  is referring to.
Please check the following link to troubleshoot your issues.
Also, in the future please raise a separate issue, else it just gets very confusing when we have completely different conversations in the same issue.

- [Troubleshooting-Linting#1-unable-to-import--pylint](https://github.com/DonJayamanne/pythonVSCode/wiki/Troubleshooting-Linting#1-unable-to-import--pylint)  
- [Python Path and Version](https://github.com/DonJayamanne/pythonVSCode/wiki/Python-Path-and-Version)  

Please ensure you have configured the python path correctly.
1. Are you using a virtual environment? (looks like you are) 
2. Is Pylint installed in the virtual environment? (if not, it needs to be) 
3. Are themodules docstring and flask installed in your virtual env? (if not, then they need to be).

If the issue persists, please create a separate issue.

**Comment by niwox** [comment]
@DonJayamanne my bad. I thought it's same issue.
re-installed pylint and it's working
Thank you

**Comment by fredrikaverpil** [comment]
I just came here to request this. I'm on [release `0.5.4`](https://github.com/DonJayamanne/pythonVSCode/releases/tag/0.5.4) and I can currently successfully specify this on Windows and the `/Scripts/python.exe` part seems to be filled in automagically:

    {
        "python.pythonPath": "${workspaceRoot}/../../virtualenvs/vscode_base",
    }

However, on my mac (10.11.6), this same syntax isn't working. If I append `/bin/python`, the linting starts to work etc.

Is this supposed to work or is this not yet fully implemented (since the issue is open and all)...?

**Comment by DonJayamanne** [comment]
Not yet, which is why the issue is open. 
Will look into this soon

**Comment by fredrikaverpil** [comment]
Ok, that would be excellent. Thanks for a great extension!

**Comment by DonJayamanne** [comment]
@petr-k , @fredrikaverpil , @niwox 
Done, this feature will be in the next release.

**Comment by fredrikaverpil** [comment]
Hi, just checking in. When can we expect the next release in order enjoy this feature?

**Comment by fredrikaverpil** [comment]
Answering myself:

> Hi, just checking in. When can we expect the next release in order enjoy this feature?

Released today.

> Also, will this fix somehow work if you're using different environment variables?

Yes.

**Comment by fredrikaverpil** [comment]
@DonJayamanne I still don't think this feature works as intended. Is this the repo where I should be posting about this, or should I create a new issue in https://github.com/Microsoft/vscode-python ?

**Comment by DonJayamanne** [comment]
Please create an issue on MS repo

**Comment by fredrikaverpil** [comment]
By the way, I solved it. Nothing wrong with the auto detection feature!
