### ISSUE TITLE
"Command 'python.python-debug.startSession' not found" strikes back in 0.6.1

### ISSUE THREAD

**Issue by akochepasov** [DonJayamanne/pythonVSCode#876]
## Environment data
VS Code version:  1.11.1
Python Extension version:  0.6.1
Python Version:   python 2.7.13 Anaconda2
OS and version:    Win 8

## Actual behavior
When trying to run a Python program via the Debugger I get a notification from VSCode saying: "command 'python.python-debug.startSession' not found". Python file is open. This is the same behavior as #708, however, the version is newer. Deleting and recreating launch.json doesn't help.
When I change the extension back to 0.5.8, the problem disappears.

## Expected  behavior
Debug should start

## Steps to reproduce:  
-  Run VS Code with python 0.6.1 installed
-  Start debugging
- Observe the error

## Settings  
Your launch.json (if dealing with debugger issues):  
```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Python",
            "type": "python",
            "request": "launch",
            "stopOnEntry": true,
            "pythonPath": "${config.python.pythonPath}",
            "program": "${file}",
            "cwd": "${workspaceRoot}",
            "debugOptions": [
                "WaitOnAbnormalExit",
                "WaitOnNormalExit",
                "RedirectOutput"
            ]
        },
        {
            "name": "PySpark",
            "type": "python",
            "request": "launch",
            "stopOnEntry": true,
            "osx": {
                "pythonPath": "${env.SPARK_HOME}/bin/spark-submit"
            },
            "windows": {
                "pythonPath": "${env.SPARK_HOME}/bin/spark-submit.cmd"
            },
            "linux": {
                "pythonPath": "${env.SPARK_HOME}/bin/spark-submit"
            },
            "program": "${file}",
            "cwd": "${workspaceRoot}",
            "debugOptions": [
                "WaitOnAbnormalExit",
                "WaitOnNormalExit",
                "RedirectOutput"
            ]
        },
        {
            "name": "Python Module",
            "type": "python",
            "request": "launch",
            "stopOnEntry": true,
            "pythonPath": "${config.python.pythonPath}",
            "module": "module.name",
            "cwd": "${workspaceRoot}",
            "debugOptions": [
                "WaitOnAbnormalExit",
                "WaitOnNormalExit",
                "RedirectOutput"
            ]
        },
        {
            "name": "Integrated Terminal/Console",
            "type": "python",
            "request": "launch",
            "stopOnEntry": true,
            "pythonPath": "${config.python.pythonPath}",
            "program": "${file}",
            "cwd": "null",
            "console": "integratedTerminal",
            "debugOptions": [
                "WaitOnAbnormalExit",
                "WaitOnNormalExit"
            ]
        },
        {
            "name": "External Terminal/Console",
            "type": "python",
            "request": "launch",
            "stopOnEntry": true,
            "pythonPath": "${config.python.pythonPath}",
            "program": "${file}",
            "cwd": "null",
            "console": "externalTerminal",
            "debugOptions": [
                "WaitOnAbnormalExit",
                "WaitOnNormalExit"
            ]
        },
        {
            "name": "Django",
            "type": "python",
            "request": "launch",
            "stopOnEntry": true,
            "pythonPath": "${config.python.pythonPath}",
            "program": "${workspaceRoot}/manage.py",
            "cwd": "${workspaceRoot}",
            "args": [
                "runserver",
                "--noreload"
            ],
            "debugOptions": [
                "WaitOnAbnormalExit",
                "WaitOnNormalExit",
                "RedirectOutput",
                "DjangoDebugging"
            ]
        },
        {
            "name": "Flask",
            "type": "python",
            "request": "launch",
            "stopOnEntry": false,
            "pythonPath": "${config.python.pythonPath}",
            "program": "fully qualified path fo 'flask' executable. Generally located along with python interpreter",
            "cwd": "${workspaceRoot}",
            "env": {
                "FLASK_APP": "${workspaceRoot}/quickstart/app.py"
            },
            "args": [
                "run",
                "--no-debugger",
                "--no-reload"
            ],
            "debugOptions": [
                "WaitOnAbnormalExit",
                "WaitOnNormalExit",
                "RedirectOutput"
            ]
        },
        {
            "name": "Flask (old)",
            "type": "python",
            "request": "launch",
            "stopOnEntry": false,
            "pythonPath": "${config.python.pythonPath}",
            "program": "${workspaceRoot}/run.py",
            "cwd": "${workspaceRoot}",
            "args": [],
            "debugOptions": [
                "WaitOnAbnormalExit",
                "WaitOnNormalExit",
                "RedirectOutput"
            ]
        },
        {
            "name": "Watson",
            "type": "python",
            "request": "launch",
            "stopOnEntry": true,
            "pythonPath": "${config.python.pythonPath}",
            "program": "${workspaceRoot}/console.py",
            "cwd": "${workspaceRoot}",
            "args": [
                "dev",
                "runserver",
                "--noreload=True"
            ],
            "debugOptions": [
                "WaitOnAbnormalExit",
                "WaitOnNormalExit",
                "RedirectOutput"
            ]
        },
        {
            "name": "Attach (Remote Debug)",
            "type": "python",
            "request": "attach",
            "localRoot": "${workspaceRoot}",
            "remoteRoot": "${workspaceRoot}",
            "port": 3000,
            "secret": "my_secret",
            "host": "localhost"
        }
    ]
}
```   

Your settings.json:   
```json
No settings.json file
```   

## Logs
Output from ```Python``` output panel  
```
NA
```   

Output from ```Console window``` (Help->Developer Tools menu)
```
NA
```

I work on detached from the internet machine and so I copy-paste VSCode and ~/.vscode directories, saving the previous as a backup. When I remove 0.6.1 plug-in and copy back old one, 0.5.8, debugging starts working.

**Comment by akochepasov** [comment]
NA means that I don't have an output to Python panel.

**Comment by akochepasov** [comment]
Found console log.
[console.txt](https://github.com/DonJayamanne/pythonVSCode/files/918230/console.txt)

**Comment by DonJayamanne** [comment]
@akochepasov please could you update the Jupyter extension to the latest version and let me know how it goes.

**Comment by DonJayamanne** [comment]
@akochepasov oops, the Jupyter extension is broken, please uninstall it for now.

**Comment by mozram** [comment]
Can confirm. Uninstalling Jupyter fix the error. Thanks!

**Comment by DonJayamanne** [comment]
Will publish a fix asap

**Comment by DonJayamanne** [comment]
@mozram 
@akochepasov 

Fixed, please reinstall Jupyter extension. 
https://github.com/DonJayamanne/vscodeJupyter/commit/c037916f204ce10a4b0d00b426038539ebb85018

Sorry about this stuff up.

**Comment by DonJayamanne** [comment]
@akochepasov , thanks for the excellent log files. Helped me identify the issue immediately. Took a while to fix as I was away for lunch.

**Comment by akochepasov** [comment]
Hi, I cannot download and reinstall the Jupyter extension today, so I just changed the local file as in commit, the version, and the timeout.  I also deleted and recreated launch.json. The debug still doesn't start. console.log and launch.json attached.

[console2.txt](https://github.com/DonJayamanne/pythonVSCode/files/920658/console2.txt)
[launch.json.txt](https://github.com/DonJayamanne/pythonVSCode/files/920659/launch.json.txt)

**Comment by akochepasov** [comment]
Update: I deleted jupyter extension and debug started working.

**Comment by DonJayamanne** [comment]
For some reason you still seem to be using the old version of the extension. Hmm.

**Comment by DonJayamanne** [comment]
I mean old version of Jupyter extension.

**Comment by akochepasov** [comment]
I do, but I changed the timeout from 10k to 20k, changed version package.json and changed directory name. The only actual fix was in timeout, wasn't it?

**Comment by DonJayamanne** [comment]
What's the version of Jupyter installed?

**Comment by akochepasov** [comment]
Fixed after internet update

**Comment by akochepasov** [comment]
Jupyter 4.2.1

**Comment by DonJayamanne** [comment]
No no I mean uninstall the Jupyter extension in vscode.

**Comment by akochepasov** [comment]
Yes, I did. I reinstalled and downloaded a new package 1.1.1. Now it's OK

**Comment by DonJayamanne** [comment]
Excellent
